
services:
  bco-api:
    platform: linux/amd64
    build: .
    container_name: bco-api
    # volumes:
    #   - ./db.sqlite3:/biocompute_api/db.sqlite3
    #   - ./.secrets:/biocompute_api/.secrets
    environment:
      TZ: 'America/New_York'

    ports:
      - "8000:8000"

    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true

