# Generated by Django 3.2.10 on 2022-01-24 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixes',
            name='certifying_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixes',
            name='certifying_server',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixes',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='prefixes',
            name='created_by',
            field=models.ForeignKey(default='wheel', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='prefixes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixes',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
