# Generated by Django 3.2.10 on 2022-01-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220124_2356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meta_table',
            new_name='prefix_table',
        ),
    ]
