# Generated by Django 3.1.7 on 2021-03-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prefix_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='px_tables',
            fields=[
                ('prefix_tables_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.prefix_tables')),
            ],
            bases=('api.prefix_tables',),
        ),
        migrations.RenameModel(
            old_name='prefixes',
            new_name='px_groups',
        ),
    ]
