# Generated by Django 3.2.10 on 2022-03-02 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rename_meta_table_prefix_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group', to_field='name')),
                ('delete_members_on_group_deletion', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('max_n_members', models.IntegerField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='NewUsers',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('temp_identifier', models.TextField(max_length=100)),
                ('token', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('prefix', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('certifying_server', models.TextField(blank=True, null=True)),
                ('certifying_key', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('n_objects', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(default='wheel', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.RemoveField(
            model_name='group_info',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_info',
            name='owner_user',
        ),
        migrations.DeleteModel(
            name='new_users',
        ),
        migrations.DeleteModel(
            name='prefix_table',
        ),
        migrations.RemoveField(
            model_name='prefixes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prefixes',
            name='owner_group',
        ),
        migrations.RemoveField(
            model_name='prefixes',
            name='owner_user',
        ),
        migrations.AlterField(
            model_name='bco',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bco',
            name='owner_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', to_field='name'),
        ),
        migrations.AlterField(
            model_name='bco',
            name='owner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.DeleteModel(
            name='group_info',
        ),
        migrations.DeleteModel(
            name='prefixes',
        ),
        migrations.AlterField(
            model_name='bco',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.prefix'),
        ),
    ]
