# Generated by Django 3.2.10 on 2022-03-22 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0004_rename_group_info_groupinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prefixes',
            new_name='Prefix',
        ),
    ]
