# Generated by Django 3.2.13 on 2024-04-02 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('prefix', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('certifying_key', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0, help_text='Counter for object_id asignment')),
                ('public', models.BooleanField(default=True, help_text='Boolean field to indicate if there are restrictions on the use of this prefix')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
